### ISSUE TITLE
Hey you can remove this while you can

### ISSUE THREAD

**Issue by AquaNot** [Volcan4436/francium-Source-Leak#2]
Hey, right now im just asking nicely i can just dmca this but im asking you nicely to remove it, if you decide not to remove it, i will terminate your whole github account

Sincerely,
Aqua.

**Comment by Volcan4436** [comment]
nah but good luck terming my account xD

**Comment by Nxrgh** [comment]
im the1 who send the src lmao

**Comment by Volcan4436** [comment]
Also this is under the Sodium License so xD

**Comment by Volcan4436** [comment]
*Threatens to DMCA* *Nothing Happens* lmao imagine
